### ISSUE TITLE
DOI attribution

### ISSUE THREAD

**Issue by chahank** [CLIMADA-project/climada_papers#3]
For scientific publications, it is often required to provide a DOI linking to the used code and/or data. The purpose of this repository is to gather precisely the code of published work that used CLIMADA. 

Proposal: make a DOI with Zenodo for the entire repository. 

- Each time a new work is added, a new release is made which is associated with a new DOI
- There is also a common single DOI for all the releases of the CLIMADA_papers repository

Question: how to set the authorship of the DOI?

1. Add all the authors of all the papers in the repository?
2. The person that adds a contribution must specificy who should be listed as author of the code.

Question: what account should manage the Zenodo account?

1. David?
2. A group account? with for instance a climada@ethz.ch

Issues:

- The author list might get very large
- The authorship between papers becomes mixed
- Single code does not get a single DOI, but the DOI is always for the whole CLIMADA_papers repository.
- The number of included papers might become very large too if the use of CLIMADA grows quickly and then finding one code in the project folder might become too cumbersome.

**Comment by ThomasRoosli** [comment]
Discussion among developers came to the following conclusion:
- The current repository will stay as is: an offer for researchers using CLIMADA to share their code used in publications.
- For creating DOIs it is recommended to create a new repository for the specific publication and create a publication specific DOI. For this GitHub and Zenodo can be used or other services like ETH library. It is highly appreciated if these repositories and the corresponding publication is listed as a link in the README file of this (the CLIMADA_papers) repository.
- If in the future anyone wants to create a DOI for this repository, they are still welcome to do so.
